### ISSUE TITLE
Blockquotes within paragraphs and incorrect structuring of quoted verses

### ISSUE THREAD

**Issue by drgrigg** [justindisney/g-k-chesterton_heretics#3]
Throughout, you have this kind of structure, for example in chapter-5:

```
<p>There is one striking instance... has been admirably expressed in a famous quotation. Addison makes the great Stoic say⁠— <blockquote><p>“ ’Tis not in mortals to command success;<br/>
But we’ll do more, Sempronius, we’ll deserve it.”</p></blockquote></p>
```

Blockquote tags should not be embedded _within_ p tags. And you need to follow the rules in the manual (7.5) about formatting and semantically tagging verse. You'll need to include the appropriate CSS from the manual. Even though these quotes are not _poems_, they should be treated as _verse_ with the same rules.

**Comment by drgrigg** [comment]
By the way, epubcheck fails during the build process because of these errors, flagging the blockquotes within p tags. Did you run a build to check the book?

**Comment by justindisney** [comment]
All blockquotes have been moved outside of the paragraph tags and have had appropriate epub type and span tags added.
