### ISSUE TITLE
Colophon credits for transcription - query

### ISSUE THREAD

**Issue by drgrigg** [justindisney/g-k-chesterton_heretics#4]
I'm not sure (@acabal may need to advise) whether we credit the person who did the HTML versions of Gutenberg books in the colophon. In any case, what you have here doesn't make sense grammatically without at least some change, as it makes it seem that only the HTML version was done for Project Gutenberg. 

```
...is based on a transcription produced in 1996 by<br/>
<b class="name">Mike Piff</b> and <b class="name">Martin Ward</b>. HTML version by <b class="name">Al Haines</b><br/>
for<br/>
<a href="https://www.gutenberg.org/ebooks/470">Project Gutenberg</a>
```

Personally, I would leave out the HTML credit entirely and just run it so it reads "by Mike Piff and Martin Ward for Project Gutenberg".

**Comment by acabal** [comment]
I would include everyone credited, but not at the level of specificity Gutenberg has. So you can just say `Mike Piff, Martin Ward, and Al Haines.`
